name: Build Linux

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:buster-slim
    env:
      VENDOR: ${{ github.workspace }}/vendor
      PREFIX: ${{ github.workspace }}/install

      OPUS_VERSION: 1.6.1
      OPUS_SHA256: 6ffcb593207be92584df15b32466ed64bbec99109f007c82205f0194572411a1

      LAME_VERSION: "3.100"
      LAME_SHA256: ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e

      X264_REVISION: b35605ace3ddf7c1a5d67a2eb553f034aef41d55
      LIBVPX_VERSION: v1.16.0
      SVTAV1_VERSION: v4.1.0
      OGG_VERSION: v1.3.6
      VORBIS_VERSION: v1.3.7
      LIBDRM_VERSION: libdrm-2.4.133
      LIBVA_VERSION: 2.23.0
      NVCODEC_VERSION: n13.0.19.0
      VULKAN_VERSION: vulkan-sdk-1.4.341.0
      FFMPEG_VERSION: n8.1

      CC: gcc
      CFLAGS: -fPIC

      PKG_CONFIG_PATH: ${{ github.workspace }}/install/lib/pkgconfig
      PKG_CONFIG: pkg-config --static

    steps:
      - name: Install build dependencies
        run: |
          # Debian buster is now EOL, need to set APT to use the package archive.
          sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list

          apt-get update
          apt-get install -y --no-install-recommends \
            coreutils \
            build-essential \
            git \
            gcc \
            g++ \
            zip \
            ca-certificates \
            pkg-config \
            libtool-bin \
            autoconf \
            automake \
            ninja-build \
            yasm \
            nasm

          # Setup Debian Bullseye PPA for newer cURL version
          echo "deb http://deb.debian.org/debian bullseye main" >> /etc/apt/sources.list
          echo "deb http://security.debian.org/debian-security bullseye-security main" >> /etc/apt/sources.list
          echo "deb http://archive.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list
          cat <<EOF > /etc/apt/preferences.d/bullseye
          Package: *
          Pin: release n=bullseye
          Pin-Priority: 100
          EOF

          apt-get update
          apt-get install -y -t bullseye curl

          # Setup Debian Bookwork PPA for newer CMake and Meson versions
          echo "deb http://deb.debian.org/debian bookworm main" >> /etc/apt/sources.list
          echo "deb http://security.debian.org/debian-security bookworm-security main" >> /etc/apt/sources.list
          cat <<EOF > /etc/apt/preferences.d/bookworm
          Package: *
          Pin: release n=bookworm
          Pin-Priority: 100
          EOF

          apt-get update
          apt-get install -y -t bookworm cmake meson

      - name: Prepare build directories
        run: |
          mkdir -p "$VENDOR" "$PREFIX"

      - name: Build libdrm
        run: |
          git init "$VENDOR/libdrm"
          git -C "$VENDOR/libdrm" fetch https://gitlab.freedesktop.org/mesa/libdrm.git "$LIBDRM_REVISION" --depth=1
          git -C "$VENDOR/libdrm" checkout FETCH_HEAD
          cd "$VENDOR/libdrm"

          meson setup build \
            --default-library=static \
            -Dprefix="$PREFIX" \
            -Dlibdir="$PREFIX/lib" \
            -Dudev=true \
            -Dvalgrind=disabled
          ninja -C build
          ninja -C build install

      - name: Build libVA
        run: |
          git init "$VENDOR/libva"
          git -C "$VENDOR/libva" fetch https://github.com/intel/libva.git "$LIBVA_VERSION" --depth=1
          git -C "$VENDOR/libva" checkout FETCH_HEAD
          cd "$VENDOR/libva"

          ./autogen.sh \
            --prefix="$PREFIX" \
            --enable-static \
            --disable-shared
          make -j$(nproc)
          make install

      - name: Build x264
        run: |
          git init "$VENDOR/x264"
          git -C "$VENDOR/x264" fetch https://code.videolan.org/videolan/x264.git $X264_REVISION --depth=1
          git -C "$VENDOR/x264" checkout FETCH_HEAD
          cd "$VENDOR/x264"

          ./configure \
            --prefix="$PREFIX" \
            --enable-static \
            --enable-pic \
            --disable-opencl \
            --disable-cli
          make -j$(nproc)
          make install

      - name: Build libvpx
        run: |
          git init "$VENDOR/libvpx"
          git -C "$VENDOR/libvpx" fetch https://chromium.googlesource.com/webm/libvpx "$LIBVPX_REVISION" --depth=1
          git -C "$VENDOR/libvpx" checkout FETCH_HEAD
          cd "$VENDOR/libvpx"

          ./configure \
            --prefix="$PREFIX" \
            --enable-vp8 \
            --enable-vp9 \
            --enable-static \
            --enable-pic \
            --disable-examples \
            --disable-unit-tests
          make -j$(nproc)
          make install

      - name: Build SVT-AV1
        run: |
          git init "$VENDOR/SVT-AV1"
          git -C "$VENDOR/SVT-AV1" fetch https://gitlab.com/AOMediaCodec/SVT-AV1 "$SVTAV1_REVISION" --depth=1
          git -C "$VENDOR/SVT-AV1" checkout FETCH_HEAD
          cd "$VENDOR/SVT-AV1"

          cmake -S . -B build -G Ninja \
            -DCMAKE_INSTALL_PREFIX="$PREFIX" \
            -DNATIVE=OFF \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build build
          cmake --install build

      - name: Build LAME
        run: |
          curl --output-dir "$VENDOR" -LO https://deac-ams.dl.sourceforge.net/project/lame/lame/${LAME_VERSION}/lame-${LAME_VERSION}.tar.gz
          echo "$LAME_SHA256 $VENDOR/lame-${LAME_VERSION}.tar.gz" | sha256sum -c

          tar xf "$VENDOR/lame-${LAME_VERSION}.tar.gz" -C "$VENDOR"
          cd "$VENDOR/lame-${LAME_VERSION}"

          ./configure \
            --prefix="$PREFIX" \
            --enable-static \
            --enable-pic \
            --disable-shared
          make -j$(nproc)
          make install

      - name: Build OPUS
        run: |
          curl --output-dir "$VENDOR" -LO https://downloads.xiph.org/releases/opus/opus-${OPUS_VERSION}.tar.gz
          echo "$OPUS_SHA256 $VENDOR/opus-${OPUS_VERSION}.tar.gz" | sha256sum -c

          tar xf "$VENDOR/opus-${OPUS_VERSION}.tar.gz" -C "$VENDOR"
          cd "$VENDOR/opus-${OPUS_VERSION}"

          ./configure \
            --prefix="$PREFIX" \
            --enable-custom-modes \
            --enable-static \
            --enable-pic \
            --disable-shared
          make -j$(nproc)
          make install

      - name: Build OGG
        run: |
          git init "$VENDOR/ogg"
          git -C "$VENDOR/ogg" fetch https://github.com/xiph/ogg.git "$OGG_VERSION" --depth=1
          git -C "$VENDOR/ogg" checkout FETCH_HEAD
          cd "$VENDOR/ogg"

          cmake -S . -B build -G Ninja \
            -DCMAKE_INSTALL_PREFIX="$PREFIX" \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build build
          cmake --install build

      - name: Build Vorbis
        run: |
          git init "$VENDOR/vorbis"
          git -C "$VENDOR/vorbis" fetch https://github.com/xiph/vorbis.git "$VORBIS_VERSION" --depth=1
          git -C "$VENDOR/vorbis" checkout FETCH_HEAD
          cd "$VENDOR/vorbis"

          ./autogen.sh
          ./configure \
            --prefix="$PREFIX" \
            --enable-static \
            --enable-pic \
            --disable-shared
          make -j$(nproc)
          make install

      - name: Install ffnvcodec-headers
        run: |
          git init "$VENDOR/ffnvcodec-headers"
          git -C "$VENDOR/ffnvcodec-headers" fetch https://git.videolan.org/git/ffmpeg/nv-codec-headers.git "$NVCODEC_VERSION" --depth=1
          git -C "$VENDOR/ffnvcodec-headers" checkout FETCH_HEAD
          cd "$VENDOR/ffnvcodec-headers"

          make PREFIX="$PREFIX"
          make PREFIX="$PREFIX" install

      - name: Install vulkan-headers
        run: |
          git init "$VENDOR/vulkan-headers"
          git -C "$VENDOR/vulkan-headers" fetch https://github.com/KhronosGroup/Vulkan-Headers.git "$VULKAN_VERSION" --depth=1
          git -C "$VENDOR/vulkan-headers" checkout FETCH_HEAD
          cd "$VENDOR/vulkan-headers"

          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX="$PREFIX" \
            -DCMAKE_SKIP_INSTALL_RPATH=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          cmake --build build
          cmake --install build

      - name: Build FFmpeg
        run: |
          git init "$VENDOR/ffmpeg"
          git -C "$VENDOR/ffmpeg" fetch https://git.ffmpeg.org/ffmpeg.git "$FFMPEG_VERSION" --depth=1
          git -C "$VENDOR/ffmpeg" checkout FETCH_HEAD
          cd "$VENDOR/ffmpeg"

          ./configure \
            --prefix="$PREFIX" \
            \
            --disable-autodetect \
            --disable-everything \
            --enable-gpl \
            \
            --enable-muxer=mp4 \
            --enable-muxer=matroska \
            --enable-muxer=mov \
            --enable-muxer=webm \
            \
            --enable-libx264 \
            --enable-encoder=libx264 \
            --enable-encoder=libx264rgb \
            --enable-parser=h264 \
            --enable-parser=hevc \
            \
            --enable-libvpx \
            --enable-encoder=libvpx_vp8 \
            --enable-parser=vp8 \
            --enable-encoder=libvpx_vp9 \
            --enable-parser=vp9 \
            \
            --enable-libsvtav1 \
            --enable-encoder=libsvtav1 \
            --enable-parser=av1 \
            \
            --enable-libmp3lame \
            --enable-encoder=aac \
            --enable-encoder=libmp3lame \
            --enable-parser=aac \
            --enable-parser=mpegaudio \
            \
            --enable-encoder=flac \
            --enable-parser=flac \
            \
            --enable-libopus \
            --enable-encoder=libopus \
            --enable-parser=opus \
            \
            --enable-libvorbis \
            --enable-encoder=libvorbis \
            --enable-parser=vorbis \
            \
            --enable-decoder=rawvideo \
            --enable-demuxer=rawvideo \
            --enable-decoder=pcm_s16le \
            --enable-demuxer=pcm_s16le \
            --enable-decoder=pcm_f32le \
            --enable-demuxer=pcm_f32le \
            \
            --enable-bsf=h264_mp4toannexb \
            --enable-bsf=aac_adtstoasc \
            \
            --enable-filter=format \
            --enable-filter=hwupload \
            --enable-filter=scale \
            \
            --enable-protocol=pipe \
            --enable-protocol=file \
            --enable-protocol=unix \
            \
            --enable-pthreads \
            \
            --enable-vaapi \
            --enable-encoder=av1_vaapi \            
            --enable-encoder=h264_vaapi \
            --enable-encoder=hevc_vaapi \
            --enable-encoder=vp8_vaapi \
            --enable-encoder=vp9_vaapi \
            \
            --enable-ffnvcodec \
            --enable-nvenc \
            --enable-encoder=av1_nvenc \
            --enable-encoder=h264_nvenc \
            --enable-encoder=hevc_nvenc \
            \
            --enable-vulkan \
            \
            --enable-libdrm \
            \
            --enable-ffmpeg \
            --enable-avcodec \
            --enable-avformat \
            --enable-avutil \
            --enable-swscale \
            --enable-swscale-alpha \
            --enable-swresample \
            \
            --disable-ffplay \
            --disable-ffprobe \
            --disable-debug \
            --disable-doc \
            --disable-htmlpages \
            --disable-manpages \
            --disable-podpages \
            --disable-txtpages \
            \
            --enable-pic \
            --enable-static \
            --disable-shared \
            --disable-asm \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$PREFIX/include -fPIC" \
            --extra-ldflags="-L$PREFIX/lib" \
            --extra-libs="-lm"
          make -j$(nproc)
          make install

      - name: Create libffmpeg.so shim
        run: |
          gcc \
            -shared \
            -o libffmpeg.so \
            -Wl,--allow-multiple-definition \
            -Wl,--whole-archive \
              "$PREFIX/lib/libavformat.a" \
              "$PREFIX/lib/libavcodec.a" \
              "$PREFIX/lib/libavutil.a" \
              "$PREFIX/lib/libswresample.a" \
              "$PREFIX/lib/libswscale.a" \
              "$PREFIX/lib/libx264.a" \
              "$PREFIX/lib/libvpx.a" \
              "$PREFIX/lib/libSvtAv1Enc.a" \
              "$PREFIX/lib/libopus.a" \
              "$PREFIX/lib/libvorbis.a" \
              "$PREFIX/lib/libvorbisenc.a" \
              "$PREFIX/lib/libvorbisfile.a" \
              "$PREFIX/lib/libogg.a" \
              "$PREFIX/lib/libmp3lame.a" \
            -Wl,--no-whole-archive \
            -lm -lpthread

      - name: Create archive
        run: |
          mkdir -p package
          cp libffmpeg.so "$PREFIX/bin/ffmpeg" package

          cd package
          zip ffmpeg-linux-x86_64.zip libffmpeg.so ffmpeg

          md5sum ffmpeg
          md5sum libffmpeg.so
          md5sum ffmpeg-linux-x86_64.zip

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          path: package/ffmpeg-linux-x86_64.zip
          archive: false
